name: fastyle_calculator
description: A new Flutter package project.
version: 1.0.0-dev.1
homepage: https://github.com/tyrcord/fastyle/packages/calculator

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
